export const GET_GEOLOCATION_REQUEST = 'GET_GEOLOCATION_REQUEST'
export const GET_GEOLOCATION_SUCCESS = 'GET_GEOLOCATION_SUCCESS'
export const GET_GEOLOCATION_FAILURE = 'GET_GEOLOCATION_FAILURE'

export const GET_CURRENT_WEATHER_REQUEST = 'GET_CURRENT_WEATHER_REQUEST'
export const GET_CURRENT_WEATHER_SUCCESS = 'GET_CURRENT_WEATHER_SUCCESS'
export const GET_CURRENT_WEATHER_FAILURE = 'GET_CURRENT_WEATHER_FAILURE'

export const GET_HOURLY_WEATHER_REQUEST = 'GET_HOURLY_WEATHER_REQUEST'
export const GET_HOURLY_WEATHER_SUCCESS = 'GET_HOURLY_WEATHER_SUCCESS'
export const GET_HOURLY_WEATHER_FAILURE = 'GET_HOURLY_WEATHER_FAILURE'

export const TOGGLE_SEARCHBAR = 'TOGGLE_SEARCHBAR'